### ISSUE TITLE
Properly handle double encoding in splunk_forwarder lambda. 

### ISSUE THREAD

**Issue by danjoneslf** [alphagov/cyber-security-cloudwatch-config#74]
In the splunk forwarder lambda we currently have to json.loads() the data twice. The first time decodes as a string of JSON and the second decodes the JSON. It looks like it's being json.dumps()'ed twice when it's sent to SNS but we're don't appear to be doing that in our code. 

It's possible that boto3 is encoding the payload with json.dumps() so we don't need to do it?

**Comment by akinnane** [comment]
Which boto3 call do you think double encodes. A lot of the Kinesis endpoints require base64 encoded data but boto3 does that for you which can result in double encoding.

**Comment by danjoneslf** [comment]
> Which boto3 call do you think double encodes. A lot of the Kinesis endpoints require base64 encoded data but boto3 does that for you which can result in double encoding.

Turned out it wasn't boto3 - it was a bit of my code I'd forgotten about until I walked Deniz through how it all worked.
