### ISSUE TITLE
Investigate failing test health notifications

### ISSUE THREAD

**Issue by detnon** [alphagov/cyber-security-cloudwatch-config#91]
Health notifications sent to `alert-controller.staging.gds-cyber-security.digital` are broken and do not currently work

**Comment by gds-ahine** [comment]
ALB ingress security-group rules defined in [Terraform](https://github.com/alphagov/cyber-security-alert-processor/blob/24c2ce593579ff3ae9cc16dd34ab0c345b652948/terraform/modules/alert_controller/alert_controller_lb.tf#L98) is to permit 0/0

Lambda has it's own access-list defined in the `ALLOW_LIST` environment variable which is already permitting the Concourse    [egress](https://cd.gds-reliability.engineering/teams/cybersecurity-tools/pipelines/info/jobs/show-available-pipeline-variables/builds/143.5)

Ingress for ALB is currently set to `213.86.153.214/32`, will re-apply staging TF.

**Comment by gds-ahine** [comment]
Appears there have been some click-ops config. Staging s3 bucket has SSE set but the prod bucket doesn't and this isn't setup in TF.

<img width="540" alt="Screenshot 2021-05-17 at 15 49 45" src="https://user-images.githubusercontent.com/31096498/118508924-85b87d00-b727-11eb-9b7e-d8dbef36d909.png">

**Comment by gds-ahine** [comment]
Removed SSE for this bucket in Staging and I've updated Concourse role to include the missing `ec2:AuthorizeSecurityGroupIngress` IAM permission, was merged in this [PR](https://github.com/alphagov/cyber-security-terraform/pull/347).
